feat: adicionando condicional de cobertura minima para o deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,6 +6,33 @@ on:
       - main
 
 jobs:
+  test:
+    name: Run Tests
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Set up Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version: '16'
+
+    - name: Install dependencies
+      run: npm install
+
+    - name: Run tests with coverage
+      run: npm run test:prod
+
+    - name: Verify coverage
+      run: |
+        COVERAGE=$(grep -Po '^\s+statements:\s*\K[0-9.]+' coverage/lcov-report/index.html)
+        echo "Coverage: $COVERAGE%"
+        if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
+          echo "Coverage is below the required threshold."
+          exit 1
+        fi
   build:
     runs-on: ubuntu-latest
     steps:
